steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/synapse-488201/synapse/graph-generator:20260306-123846', '-f', 'graph-generator/Dockerfile', '.']
images:
  - 'us-central1-docker.pkg.dev/synapse-488201/synapse/graph-generator:20260306-123846'
