steps:
  # 1. Build & Push API
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/synapse/api:${_TAG}', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/synapse/api:latest', '-f', 'backend/Dockerfile', '.']

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/synapse/api:${_TAG}'

substitutions:
  _REGION: us-central1
  _TAG: latest
