import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const AgentConfig = ({ agent, brandName, onChange, onBrandChange }) => {
    return (_jsxs("div", { className: "agent-config", children: [_jsx("h2", { className: "text-2xl font-bold mb-6", children: "Agent Personality Protocol" }), _jsx("p", { className: "text-slate-400 mb-8", children: "Define the neural identity and conversational boundaries for this tenant." }), _jsxs("div", { className: "form-group", children: [_jsx("label", { className: "label", children: "Neural Brand Identifier" }), _jsx("input", { className: "input", value: brandName, onChange: e => onBrandChange(e.target.value), placeholder: "e.g. Acme Intelligence" }), _jsx("p", { className: "text-[11px] text-slate-500 mt-2 italic", children: "The agent will prioritize this identity in all multimodal interactions." })] }), _jsxs("div", { className: "form-group", children: [_jsx("label", { className: "label", children: "Operational Perspectives" }), _jsx("div", { className: "grid grid-cols-2 gap-3", children: ['csm', 'sales', 'support', 'strategy'].map((role, idx) => (_jsxs("label", { className: `
                            glass-card flex items-center gap-4 p-4 cursor-pointer transition-all duration-300
                            ${agent.roles.includes(role) ? 'border-primary-purple bg-primary-purple/10' : 'opacity-60 hover:opacity-100'}
                            stagger-${idx + 1}
                        `, children: [_jsx("input", { type: "checkbox", className: "w-4 h-4 rounded border-white/20 bg-white/5 text-primary-purple focus:ring-primary-purple", checked: agent.roles.includes(role), onChange: e => {
                                        const nextRoles = e.target.checked
                                            ? [...agent.roles, role]
                                            : agent.roles.filter(r => r !== role);
                                        onChange({ ...agent, roles: nextRoles });
                                    } }), _jsx("span", { className: "uppercase text-[11px] font-black tracking-widest", children: role })] }, role))) })] }), _jsxs("div", { className: "form-group", children: [_jsx("label", { className: "label", children: "Persona Bias Overlay" }), _jsx("textarea", { className: "textarea", rows: 4, value: agent.persona, onChange: e => onChange({ ...agent, persona: e.target.value }), placeholder: "Define the specific tone, empathy level, and technical depth..." })] }), _jsxs("div", { className: "glass-card p-6 bg-primary-purple/5 border-dashed border-primary-purple/30 relative overflow-hidden group", children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-br from-primary-purple/10 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-700" }), _jsx("h4", { className: "text-primary-purple font-black text-[10px] uppercase tracking-widest mb-3 relative z-10", children: "Live Identity Preview" }), _jsxs("p", { className: "text-sm italic text-slate-300 leading-relaxed relative z-10", children: ["\"Initializing session. I am your **", brandName || 'Synapse', "** neural operative. Account health metrics are now synchronized...\""] })] })] }));
};
export default AgentConfig;
